# Generated by Django 2.1.4 on 2018-12-30 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181230_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
