# Generated by Django 2.1.4 on 2018-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181230_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
